## Power Energy (PE) prediction using artificial neural network

In [5]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 7.6 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.7 MB 5.2 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.7 MB 4.8 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.7 MB 5.5 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.7 MB 5.5 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.7 MB 5.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 5.5 MB/s  0:00:01
Downloading numpy-2.4.3-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 7.4 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.3 MB 6.5 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.3 MB 6.8 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 7.5 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.3 MB 7.6 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 7.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 7.2 MB/s  0:00:01
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
path=r'https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/PowerPlant.csv'
df=pd.read_csv(path)
df

         AT      V       AP     RH      PE
0      8.34  40.77  1010.84  90.01  480.48
1     23.64  58.49  1011.40  74.20  445.75
2     29.74  56.90  1007.15  41.91  438.76
3     19.07  49.69  1007.22  76.79  453.09
4     11.80  40.66  1017.13  97.20  464.43
...     ...    ...      ...    ...     ...
9563  15.12  48.92  1011.80  72.93  462.59
9564  33.41  77.95  1010.30  59.72  432.90
9565  15.99  43.34  1014.20  78.66  465.96
9566  17.65  59.87  1018.58  94.65  450.93
9567  23.68  51.30  1011.86  71.24  451.67

[9568 rows x 5 columns]

## Perform basic data quality checks

In [7]:
df.shape

(9568, 5)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB

In [9]:
df.duplicated().sum()

np.int64(41)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

## Separate X and Y features

In [13]:
df.columns

Index(['AT', 'V', 'AP', 'RH', 'PE'], dtype='str')

In [14]:
df.dtypes

AT    float64
V     float64
AP    float64
RH    float64
PE    float64
dtype: object

In [15]:
X = df.drop(columns='PE')
Y=df[['PE']]

In [16]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [17]:
Y.head()

       PE
0  480.48
1  445.75
2  438.76
3  453.09
4  464.43

In [18]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from scikit-learn) (2.4.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
    --------------------------------------- 0.8/36.5 MB 3.8 MB/s eta 0:00:10
   -- ------------------------------------- 1.8/36.5 MB 5.0 MB/s eta 0:00:07
   --- ------------------------------------ 2.9/36.5 MB 4.9 MB/s eta 0:00:07
   ---- ----------------------------------- 3.9/36.5 MB 4.9 MB/s eta 0:00:07
   ----- ---------------------------------- 5.0/36.5 MB 4.9 MB/s eta 0:00:07
   ------ --------------------------------- 5.8/36.5 MB 4.7 MB/s eta 0:00:07
   -------- ------------------------------- 7.3/36.5 MB 5.1 MB/s eta 0:00:06
   -------- ------------------------------- 7.9/36.5 MB 4.9 MB/s eta 0:00:06
   --------- ------------------------------ 8.9/36.5 MB 4.9 MB/s eta 0:00:06
   ----------- ---------------------------- 10.2/36.5 MB 4.9 MB/s eta 0:00:06
   ------------ --------------------------- 11.3/36.5 MB 5.0 MB/s eta 0:00:06
   ------------- -------------------------- 12.3/36.5 MB 5.0 MB/s eta 0:00:05
   --------------- ------------------------ 13.9/36.5 MB 5.2 MB/s eta 0:00:05
   ---------------- ----------------------- 14.9/36.5 MB 5.2 MB/s eta 0:00:05
   ----------------- ---------------------- 16.0/36.5 MB 5.2 MB/s eta 0:00:04
   ------------------ --------------------- 17.0/36.5 MB 5.2 MB/s eta 0:00:04
   ------------------- -------------------- 17.8/36.5 MB 5.0 MB/s eta 0:00:04
   -------------------- ------------------- 18.9/36.5 MB 5.1 MB/s eta 0:00:04
   ---------------------- ----------------- 20.2/36.5 MB 5.1 MB/s eta 0:00:04
   ----------------------- ---------------- 21.2/36.5 MB 5.1 MB/s eta 0:00:03
   ------------------------ --------------- 22.5/36.5 MB 5.2 MB/s eta 0:00:03
   ------------------------- -------------- 23.6/36.5 MB 5.1 MB/s eta 0:00:03
   -------------------------- ------------- 24.6/36.5 MB 5.1 MB/s eta 0:00:03
   ---------------------------- ----------- 25.7/36.5 MB 5.2 MB/s eta 0:00:03
   ----------------------------- ---------- 27.0/36.5 MB 5.2 MB/s eta 0:00:02
   ------------------------------ --------- 27.8/36.5 MB 5.1 MB/s eta 0:00:02
   ------------------------------- -------- 29.1/36.5 MB 5.2 MB/s eta 0:00:02
   --------------------------------- ------ 30.1/36.5 MB 5.2 MB/s eta 0:00:02
   --------------------------------- ------ 30.7/36.5 MB 5.1 MB/s eta 0:00:02
   ---------------------------------- ----- 31.7/36.5 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 32.8/36.5 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 33.8/36.5 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 4.8 MB/s  0:00:07
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Feature Engineering : Data Preprocessing - Data Cleaning and Data Scaling

In [19]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
pre = make_pipeline(
    SimpleImputer(strategy='mean'),
    StandardScaler()
).set_output(transform='pandas')

## Split the data into training and testing

In [20]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,train_size=0.75,random_state=42)
xtrain = pre.fit_transform(xtrain)
xtest = pre.transform(xtest)

In [21]:
xtrain

            AT         V        AP        RH
1845 -0.895454 -0.799581  0.961864  0.844760
8505  0.936216  0.953401 -1.272911 -0.564076
8152 -0.966888 -0.970315  0.729110  0.563540
5023  0.138314  0.433329  0.983790  0.488959
1744 -1.224319 -0.971102 -2.262958  1.596048
...        ...       ...       ...       ...
5742 -0.116421 -1.067878 -1.360615  1.308670
5197  1.476687  1.526976 -1.706373  0.325427
5396  0.011621 -0.249610 -0.755118  1.463307
860   0.946999  1.139085 -0.421167 -0.445020
7292 -0.205376 -0.330650 -0.510558  1.806107

[7145 rows x 4 columns]

In [22]:
ytrain

          PE
1845  469.02
8505  436.65
8152  469.18
5023  445.18
1744  472.41
...      ...
5742  459.96
5197  430.00
5396  447.96
860   440.45
7292  451.14

[7145 rows x 1 columns]

## Model Building

In [24]:
pip install keras

Collecting keras
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Collecting absl-py (from keras)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: numpy in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from keras) (2.4.3)
Collecting rich (from keras)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting h5py (from keras)
  Downloading h5py-3.16.0-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Collecting optree (from keras)
  Downloading optree-0.19.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Collecting ml-dtypes (from keras)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: packaging in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from keras) (26.0)
Collecting typing-extensions>=4.6.0 (from optree->keras)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from rich->keras) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading keras-3.13.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 3.8 MB/s  0:00:00
Downloading absl_py-2.4.0-py3-none-any.whl (135 kB)
Downloading h5py-3.16.0-cp313-cp313-win_amd64.whl (3.2 MB)
   ---------------------------------------- 0.0/3.2 MB ? eta -:--:--
   ------------- -------------------------- 1.0/3.2 MB 5.7 MB/s eta 0:00:01
   ------------------- -------------------- 1.6/3.2 MB 4.5 MB/s eta 0:00:01
   ------------------------------------ --- 2.9/3.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 3.2/3.2 MB 4.3 MB/s  0:00:00
Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl (212 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.0-cp313-cp313-win_amd64.whl (337 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, typing-extensions, ml-dtypes, mdurl, h5py, absl-py, optree, markdown-it-py, rich, keras

   ----------------------------------------  0/10 [namex]
   ---- -----------------------------------  1/10 [typing-extensions]
   -------- -------------------------------  2/10 [ml-dtypes]
   ------------ ---------------------------  3/10 [mdurl]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   ---------------- -----------------------  4/10 [h5py]
   -------------------- -------------------  5/10 [absl-py]
   -------------------- -------------------  5/10 [absl-py]
   -------------------- -------------------  5/10 [absl-py]
   -------------------- -------------------  5/10 [absl-py]
   -------------------- -------------------  5/10 [absl-py]
   -------------------- -------------------  5/10 [absl-py]
   ------------------------ ---------------  6/10 [optree]
   ------------------------ ---------------  6/10 [optree]
   ------------------------ ---------------  6/10 [optree]
   ------------------------ ---------------  6/10 [optree]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [markdown-it-py]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   -------------------------------- -------  8/10 [rich]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ------------------------------------ ---  9/10 [keras]
   ---------------------------------------- 10/10 [keras]

Successfully installed absl-py-2.4.0 h5py-3.16.0 keras-3.13.2 markdown-it-py-4.0.0 mdurl-0.1.2 ml-dtypes-0.5.4 namex-0.1.0 optree-0.19.0 rich-14.3.3 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (2.4.0)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (26.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting requests<3,>=2.21.0 (from tensorflow)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting setuptools (from tensorflow)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.12.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.1.2-cp313-cp313-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: keras>=3.12.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (2.4.3)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from tensorflow) (0.5.4)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorflow)
  Downloading charset_normalizer-3.4.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorflow)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.21.0->tensorflow)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorflow)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: rich in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (14.3.3)
Requirement already satisfied: namex in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\orbad\desktop\ai projects\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/351.2 MB 3.0 MB/s eta 0:01:57
   ---------------------------------------- 1.3/351.2 MB 3.9 MB/s eta 0:01:31
   ---------------------------------------- 2.1/351.2 MB 4.0 MB/s eta 0:01:27
   ---------------------------------------- 3.1/351.2 MB 4.5 MB/s eta 0:01:18
    --------------------------------------- 4.5/351.2 MB 4.5 MB/s eta 0:01:18
    --------------------------------------- 5.2/351.2 MB 4.4 MB/s eta 0:01:19
    --------------------------------------- 6.3/351.2 MB 4.7 MB/s eta 0:01:14
    --------------------------------------- 7.3/351.2 MB 4.5 MB/s eta 0:01:16
    --------------------------------------- 8.4/351.2 MB 4.6 MB/s eta 0:01:16
   - -------------------------------------- 9.7/351.2 MB 4.8 MB/s eta 0:01:12
   - -------------------------------------- 10.5/351.2 MB 4.7 MB/s eta 0:01:13
   - -------------------------------------- 11.5/351.2 MB 4.7 MB/s eta 0:01:12
   - -------------------------------------- 12.8/351.2 MB 4.8 MB/s eta 0:01:11
   - -------------------------------------- 13.6/351.2 MB 4.8 MB/s eta 0:01:11
   - -------------------------------------- 14.7/351.2 MB 4.7 MB/s eta 0:01:12
   - -------------------------------------- 15.7/351.2 MB 4.8 MB/s eta 0:01:10
   - -------------------------------------- 16.8/351.2 MB 4.8 MB/s eta 0:01:10
   -- ------------------------------------- 17.8/351.2 MB 4.9 MB/s eta 0:01:09
   -- ------------------------------------- 18.9/351.2 MB 4.8 MB/s eta 0:01:09
   -- ------------------------------------- 19.7/351.2 MB 4.8 MB/s eta 0:01:10
   -- ------------------------------------- 21.0/351.2 MB 4.8 MB/s eta 0:01:09
   -- ------------------------------------- 22.0/351.2 MB 4.8 MB/s eta 0:01:09
   -- ------------------------------------- 22.8/351.2 MB 4.8 MB/s eta 0:01:08
   -- ------------------------------------- 23.9/351.2 MB 4.8 MB/s eta 0:01:09
   -- ------------------------------------- 25.2/351.2 MB 4.8 MB/s eta 0:01:08
   -- ------------------------------------- 25.7/351.2 MB 4.8 MB/s eta 0:01:08
   --- ------------------------------------ 27.0/351.2 MB 4.8 MB/s eta 0:01:08
   --- ------------------------------------ 28.0/351.2 MB 4.8 MB/s eta 0:01:07
   --- ------------------------------------ 29.4/351.2 MB 4.9 MB/s eta 0:01:07
   --- ------------------------------------ 30.4/351.2 MB 4.9 MB/s eta 0:01:06
   --- ------------------------------------ 31.2/351.2 MB 4.9 MB/s eta 0:01:06
   --- ------------------------------------ 32.2/351.2 MB 4.8 MB/s eta 0:01:06
   --- ------------------------------------ 33.3/351.2 MB 4.8 MB/s eta 0:01:06
   --- ------------------------------------ 34.1/351.2 MB 4.8 MB/s eta 0:01:06
   ---- ----------------------------------- 35.4/351.2 MB 4.9 MB/s eta 0:01:05
   ---- ----------------------------------- 36.7/351.2 MB 4.9 MB/s eta 0:01:05
   ---- ----------------------------------- 37.7/351.2 MB 4.9 MB/s eta 0:01:04
   ---- ----------------------------------- 38.8/351.2 MB 4.9 MB/s eta 0:01:04
   ---- ----------------------------------- 40.1/351.2 MB 4.9 MB/s eta 0:01:04
   ---- ----------------------------------- 41.4/351.2 MB 5.0 MB/s eta 0:01:03
   ---- ----------------------------------- 42.5/351.2 MB 5.0 MB/s eta 0:01:03
   ---- ----------------------------------- 43.3/351.2 MB 5.0 MB/s eta 0:01:02
   ----- ---------------------------------- 44.6/351.2 MB 5.0 MB/s eta 0:01:02
   ----- ---------------------------------- 44.6/351.2 MB 5.0 MB/s eta 0:01:02
   ----- ---------------------------------- 44.6/351.2 MB 5.0 MB/s eta 0:01:02
   ----- ---------------------------------- 47.2/351.2 MB 4.9 MB/s eta 0:01:02
   ----- ---------------------------------- 48.0/351.2 MB 4.9 MB/s eta 0:01:02
   ----- ---------------------------------- 49.0/351.2 MB 4.9 MB/s eta 0:01:02
   ----- ---------------------------------- 50.3/351.2 MB 4.9 MB/s eta 0:01:02
   ----- ---------------------------------- 51.4/351.2 MB 4.9 MB/s eta 0:01:01
   ----- ---------------------------------- 52.2/351.2 MB 4.9 MB/s eta 0:01:01
   ------ --------------------------------- 53.2/351.2 MB 4.9 MB/s eta 0:01:01
   ------ --------------------------------- 54.3/351.2 MB 4.9 MB/s eta 0:01:01
   ------ --------------------------------- 55.6/351.2 MB 4.9 MB/s eta 0:01:00
   ------ --------------------------------- 56.6/351.2 MB 4.9 MB/s eta 0:01:00
   ------ --------------------------------- 57.7/351.2 MB 4.9 MB/s eta 0:01:00
   ------ --------------------------------- 59.0/351.2 MB 5.0 MB/s eta 0:00:59
   ------ --------------------------------- 59.8/351.2 MB 4.9 MB/s eta 0:00:59
   ------ --------------------------------- 61.1/351.2 MB 5.0 MB/s eta 0:00:59
   ------- -------------------------------- 62.4/351.2 MB 5.0 MB/s eta 0:00:59
   ------- -------------------------------- 63.4/351.2 MB 5.0 MB/s eta 0:00:58
   ------- -------------------------------- 64.2/351.2 MB 5.0 MB/s eta 0:00:58
   ------- -------------------------------- 65.3/351.2 MB 5.0 MB/s eta 0:00:58
   ------- -------------------------------- 66.3/351.2 MB 5.0 MB/s eta 0:00:58
   ------- -------------------------------- 67.9/351.2 MB 5.0 MB/s eta 0:00:57
   ------- -------------------------------- 68.9/351.2 MB 5.0 MB/s eta 0:00:57
   ------- -------------------------------- 69.5/351.2 MB 5.0 MB/s eta 0:00:57
   ------- -------------------------------- 69.5/351.2 MB 5.0 MB/s eta 0:00:57
   -------- ------------------------------- 71.8/351.2 MB 5.0 MB/s eta 0:00:57
   -------- ------------------------------- 72.9/351.2 MB 5.0 MB/s eta 0:00:56
   -------- ------------------------------- 74.2/351.2 MB 5.0 MB/s eta 0:00:56
   -------- ------------------------------- 75.2/351.2 MB 5.0 MB/s eta 0:00:56
   -------- ------------------------------- 76.5/351.2 MB 5.0 MB/s eta 0:00:55
   -------- ------------------------------- 77.9/351.2 MB 5.0 MB/s eta 0:00:55
   -------- ------------------------------- 78.4/351.2 MB 5.0 MB/s eta 0:00:55
   --------- ------------------------------ 79.7/351.2 MB 5.0 MB/s eta 0:00:55
   --------- ------------------------------ 80.7/351.2 MB 5.0 MB/s eta 0:00:54
   --------- ------------------------------ 81.8/351.2 MB 5.0 MB/s eta 0:00:54
   --------- ------------------------------ 83.1/351.2 MB 5.0 MB/s eta 0:00:54
   --------- ------------------------------ 84.1/351.2 MB 5.0 MB/s eta 0:00:54
   --------- ------------------------------ 85.2/351.2 MB 5.0 MB/s eta 0:00:53
   --------- ------------------------------ 86.2/351.2 MB 5.0 MB/s eta 0:00:53
   --------- ------------------------------ 87.6/351.2 MB 5.0 MB/s eta 0:00:53
   ---------- ----------------------------- 88.6/351.2 MB 5.1 MB/s eta 0:00:52
   ---------- ----------------------------- 90.2/351.2 MB 5.1 MB/s eta 0:00:52
   ---------- ----------------------------- 91.0/351.2 MB 5.1 MB/s eta 0:00:52
   ---------- ----------------------------- 91.8/351.2 MB 5.0 MB/s eta 0:00:52
   ---------- ----------------------------- 93.1/351.2 MB 5.1 MB/s eta 0:00:52
   ---------- ----------------------------- 94.1/351.2 MB 5.0 MB/s eta 0:00:51
   ---------- ----------------------------- 95.4/351.2 MB 5.1 MB/s eta 0:00:51
   ---------- ----------------------------- 96.5/351.2 MB 5.1 MB/s eta 0:00:51
   ----------- ---------------------------- 97.5/351.2 MB 5.1 MB/s eta 0:00:51
   ----------- ---------------------------- 98.6/351.2 MB 5.1 MB/s eta 0:00:50
   ----------- ---------------------------- 99.9/351.2 MB 5.1 MB/s eta 0:00:50
   ----------- ---------------------------- 100.7/351.2 MB 5.1 MB/s eta 0:00:50
   ----------- ---------------------------- 102.0/351.2 MB 5.1 MB/s eta 0:00:50
   ----------- ---------------------------- 103.0/351.2 MB 5.1 MB/s eta 0:00:49
   ----------- ---------------------------- 104.1/351.2 MB 5.1 MB/s eta 0:00:49
   ----------- ---------------------------- 104.9/351.2 MB 5.1 MB/s eta 0:00:49
   ------------ --------------------------- 105.9/351.2 MB 5.1 MB/s eta 0:00:49
   ------------ --------------------------- 107.0/351.2 MB 5.1 MB/s eta 0:00:49
   ------------ --------------------------- 108.0/351.2 MB 5.1 MB/s eta 0:00:48
   ------------ --------------------------- 109.1/351.2 MB 5.1 MB/s eta 0:00:48
   ------------ --------------------------- 110.4/351.2 MB 5.1 MB/s eta 0:00:48
   ------------ --------------------------- 111.1/351.2 MB 5.1 MB/s eta 0:00:48
   ------------ --------------------------- 111.9/351.2 MB 5.1 MB/s eta 0:00:48
   ------------ --------------------------- 113.2/351.2 MB 5.1 MB/s eta 0:00:48
   ------------- -------------------------- 114.3/351.2 MB 5.1 MB/s eta 0:00:47
   ------------- -------------------------- 115.3/351.2 MB 5.1 MB/s eta 0:00:47
   ------------- -------------------------- 116.4/351.2 MB 5.1 MB/s eta 0:00:47
   ------------- -------------------------- 117.4/351.2 MB 5.1 MB/s eta 0:00:47
   ------------- -------------------------- 118.8/351.2 MB 5.1 MB/s eta 0:00:46
   ------------- -------------------------- 119.8/351.2 MB 5.1 MB/s eta 0:00:46
   ------------- -------------------------- 120.8/351.2 MB 5.1 MB/s eta 0:00:46
   ------------- -------------------------- 122.2/351.2 MB 5.1 MB/s eta 0:00:46
   -------------- ------------------------- 123.2/351.2 MB 5.1 MB/s eta 0:00:45
   -------------- ------------------------- 124.3/351.2 MB 5.1 MB/s eta 0:00:45
   -------------- ------------------------- 124.8/351.2 MB 5.1 MB/s eta 0:00:45
   -------------- ------------------------- 125.8/351.2 MB 5.0 MB/s eta 0:00:45
   -------------- ------------------------- 126.9/351.2 MB 5.1 MB/s eta 0:00:45
   -------------- ------------------------- 128.2/351.2 MB 5.1 MB/s eta 0:00:45
   -------------- ------------------------- 129.2/351.2 MB 5.1 MB/s eta 0:00:44
   -------------- ------------------------- 130.3/351.2 MB 5.1 MB/s eta 0:00:44
   -------------- ------------------------- 131.3/351.2 MB 5.0 MB/s eta 0:00:44
   --------------- ------------------------ 132.1/351.2 MB 5.0 MB/s eta 0:00:44
   --------------- ------------------------ 133.2/351.2 MB 5.0 MB/s eta 0:00:44
   --------------- ------------------------ 134.5/351.2 MB 5.0 MB/s eta 0:00:43
   --------------- ------------------------ 135.0/351.2 MB 5.0 MB/s eta 0:00:44
   --------------- ------------------------ 136.3/351.2 MB 5.0 MB/s eta 0:00:43
   --------------- ------------------------ 137.1/351.2 MB 5.0 MB/s eta 0:00:43
   --------------- ------------------------ 138.4/351.2 MB 5.0 MB/s eta 0:00:43
   --------------- ------------------------ 139.5/351.2 MB 5.0 MB/s eta 0:00:43
   ---------------- ----------------------- 140.5/351.2 MB 5.0 MB/s eta 0:00:42
   ---------------- ----------------------- 141.6/351.2 MB 5.0 MB/s eta 0:00:42
   ---------------- ----------------------- 142.6/351.2 MB 5.0 MB/s eta 0:00:42
   ---------------- ----------------------- 143.4/351.2 MB 5.0 MB/s eta 0:00:42
   ---------------- ----------------------- 144.7/351.2 MB 5.0 MB/s eta 0:00:42
   ---------------- ----------------------- 146.0/351.2 MB 5.0 MB/s eta 0:00:41
   ---------------- ----------------------- 147.1/351.2 MB 5.0 MB/s eta 0:00:41
   ---------------- ----------------------- 148.4/351.2 MB 5.0 MB/s eta 0:00:41
   ---------------- ----------------------- 149.2/351.2 MB 5.0 MB/s eta 0:00:41
   ----------------- ---------------------- 150.2/351.2 MB 5.0 MB/s eta 0:00:40
   ----------------- ---------------------- 151.3/351.2 MB 5.0 MB/s eta 0:00:40
   ----------------- ---------------------- 152.3/351.2 MB 5.1 MB/s eta 0:00:40
   ----------------- ---------------------- 153.4/351.2 MB 5.1 MB/s eta 0:00:40
   ----------------- ---------------------- 154.4/351.2 MB 5.1 MB/s eta 0:00:39
   ----------------- ---------------------- 155.2/351.2 MB 5.1 MB/s eta 0:00:39
   ----------------- ---------------------- 156.2/351.2 MB 5.1 MB/s eta 0:00:39
   ----------------- ---------------------- 157.3/351.2 MB 5.0 MB/s eta 0:00:39
   ------------------ --------------------- 158.3/351.2 MB 5.1 MB/s eta 0:00:39
   ------------------ --------------------- 159.9/351.2 MB 5.1 MB/s eta 0:00:38
   ------------------ --------------------- 160.7/351.2 MB 5.1 MB/s eta 0:00:38
   ------------------ --------------------- 161.5/351.2 MB 5.1 MB/s eta 0:00:38
   ------------------ --------------------- 162.5/351.2 MB 5.0 MB/s eta 0:00:38
   ------------------ --------------------- 163.6/351.2 MB 5.0 MB/s eta 0:00:38
   ------------------ --------------------- 164.6/351.2 MB 5.0 MB/s eta 0:00:37
   ------------------ --------------------- 165.9/351.2 MB 5.1 MB/s eta 0:00:37
   ------------------- -------------------- 167.0/351.2 MB 5.1 MB/s eta 0:00:37
   ------------------- -------------------- 168.3/351.2 MB 5.1 MB/s eta 0:00:37
   ------------------- -------------------- 169.3/351.2 MB 5.1 MB/s eta 0:00:36
   ------------------- -------------------- 170.1/351.2 MB 5.1 MB/s eta 0:00:36
   ------------------- -------------------- 171.2/351.2 MB 5.1 MB/s eta 0:00:36
   ------------------- -------------------- 172.2/351.2 MB 5.1 MB/s eta 0:00:36
   ------------------- -------------------- 173.3/351.2 MB 5.1 MB/s eta 0:00:36
   ------------------- -------------------- 174.3/351.2 MB 5.1 MB/s eta 0:00:35
   ------------------- -------------------- 175.4/351.2 MB 5.1 MB/s eta 0:00:35
   -------------------- ------------------- 176.2/351.2 MB 5.1 MB/s eta 0:00:35
   -------------------- ------------------- 177.5/351.2 MB 5.1 MB/s eta 0:00:35
   -------------------- ------------------- 178.5/351.2 MB 5.1 MB/s eta 0:00:35
   -------------------- ------------------- 179.0/351.2 MB 5.1 MB/s eta 0:00:35
   -------------------- ------------------- 180.1/351.2 MB 5.0 MB/s eta 0:00:34
   -------------------- ------------------- 181.1/351.2 MB 5.0 MB/s eta 0:00:34
   -------------------- ------------------- 182.2/351.2 MB 5.0 MB/s eta 0:00:34
   -------------------- ------------------- 183.2/351.2 MB 5.0 MB/s eta 0:00:34
   -------------------- ------------------- 184.0/351.2 MB 5.0 MB/s eta 0:00:34
   --------------------- ------------------ 185.3/351.2 MB 5.0 MB/s eta 0:00:33
   --------------------- ------------------ 186.1/351.2 MB 5.0 MB/s eta 0:00:33
   --------------------- ------------------ 186.9/351.2 MB 5.0 MB/s eta 0:00:33
   --------------------- ------------------ 188.5/351.2 MB 5.0 MB/s eta 0:00:33
   --------------------- ------------------ 189.3/351.2 MB 5.0 MB/s eta 0:00:33
   --------------------- ------------------ 190.3/351.2 MB 5.0 MB/s eta 0:00:33
   --------------------- ------------------ 191.4/351.2 MB 5.0 MB/s eta 0:00:32
   --------------------- ------------------ 192.2/351.2 MB 5.0 MB/s eta 0:00:32
   ---------------------- ----------------- 193.5/351.2 MB 5.0 MB/s eta 0:00:32
   ---------------------- ----------------- 194.5/351.2 MB 5.0 MB/s eta 0:00:32
   ---------------------- ----------------- 194.8/351.2 MB 5.1 MB/s eta 0:00:31
   ---------------------- ----------------- 194.8/351.2 MB 5.1 MB/s eta 0:00:31
   ---------------------- ----------------- 197.4/351.2 MB 5.0 MB/s eta 0:00:31
   ---------------------- ----------------- 198.2/351.2 MB 5.0 MB/s eta 0:00:31
   ---------------------- ----------------- 199.2/351.2 MB 5.0 MB/s eta 0:00:31
   ---------------------- ----------------- 200.3/351.2 MB 5.0 MB/s eta 0:00:31
   ---------------------- ----------------- 201.3/351.2 MB 5.0 MB/s eta 0:00:30
   ----------------------- ---------------- 202.6/351.2 MB 5.0 MB/s eta 0:00:30
   ----------------------- ---------------- 203.4/351.2 MB 5.0 MB/s eta 0:00:30
   ----------------------- ---------------- 204.7/351.2 MB 5.0 MB/s eta 0:00:30
   ----------------------- ---------------- 205.8/351.2 MB 5.0 MB/s eta 0:00:30
   ----------------------- ---------------- 206.8/351.2 MB 5.0 MB/s eta 0:00:29

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
from keras.models import Sequential
from keras.layers import Input,Dense,BatchNormalization,Dropout
from keras.callbacks import EarlyStopping

## Forward Propogation

In [28]:
# Initialize the model
model= Sequential()

# add the input layer
model.add(Input(shape=(xtrain.shape[1],)))

# Add the hidden layer 1
model.add(Dense(units=64,activation='relu'))

# Add the hidden layer 2
model.add(Dense(units=32,activation='relu'))

model.add(Dense(units=16, activation='relu'))

# Add the output layer
model.add(Dense(units=ytrain.shape[1],activation='linear'))

## Backward Propogation

In [29]:
model.compile(optimizer='adam',loss='mse',metrics=['mae'])
es = EarlyStopping(monitor='val_loss',patience=10)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [30]:
nn=model.fit(xtrain,ytrain,validation_split=0.2,epochs=200,callbacks=[es])

Epoch 1/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 160590.6719 - mae: 390.5192 - val_loss: 31042.1973 - val_mae: 152.2094
Epoch 2/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14078.9502 - mae: 98.4404 - val_loss: 7365.2988 - val_mae: 71.5467
Epoch 3/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4312.8140 - mae: 54.0215 - val_loss: 2400.0261 - val_mae: 40.0989
Epoch 4/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1622.7899 - mae: 32.4486 - val_loss: 1039.2336 - val_mae: 25.8850
Epoch 5/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 763.4624 - mae: 21.8395 - val_loss: 523.5532 - val_mae: 18.2580
Epoch 6/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 405.2773 - mae: 15.6687 - val_loss: 297.6137 - val_mae: 13.3322
Epoch 7/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 237.5043 - mae: 11.8666 - val_loss: 179.0421 - val_mae: 10.3322
Epoch 8/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 149.7322 - mae: 9.3485 - val_loss: 119.0541 - val_mae: 8.4507
Epoch 9/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 103.3113 - mae: 7.7602 - val_loss: 82.7378 - val_mae: 7.0259
Epoch 10/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 75.8824 - mae: 6.6259 - val_loss: 62.4772 - val_mae: 6.1146
Epoch 11/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 58.0574 - mae: 5.7803 - val_loss: 49.4045 - val_mae: 5.3866
Epoch 12/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 46.6883 - mae: 5.2016 - val_loss: 42.1775 - val_mae: 4.9821
Epoch 13/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39.2026 - mae: 4.7847 - val_loss: 35.6568 - val_mae: 4.5986
Epoch 14/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34.2598 - mae: 4.5059 - val_loss: 31.4629 - val_mae: 4.3277
Epoch 15/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.7975 - mae: 4.2779 - val_loss: 29.1557 - val_mae: 4.2001
Epoch 16/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28.1962 - mae: 4.1109 - val_loss: 27.7344 - val_mae: 4.0735
Epoch 17/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.4219 - mae: 3.9959 - val_loss: 25.0249 - val_mae: 3.8635
Epoch 18/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.7967 - mae: 3.8723 - val_loss: 24.0220 - val_mae: 3.7948
Epoch 19/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.6059 - mae: 3.7975 - val_loss: 23.7279 - val_mae: 3.7444
Epoch 20/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 22.8411 - mae: 3.7502 - val_loss: 23.0156 - val_mae: 3.7260
Epoch 21/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 22.1923 - mae: 3.7050 - val_loss: 21.9071 - val_mae: 3.6178
Epoch 22/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 21.5901 - mae: 3.6521 - val_loss: 21.3731 - val_mae: 3.5729
Epoch 23/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3232 - mae: 3.6320 - val_loss: 21.4072 - val_mae: 3.5773
Epoch 24/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 21.0186 - mae: 3.6252 - val_loss: 20.6975 - val_mae: 3.5333
Epoch 25/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5340 - mae: 3.5772 - val_loss: 20.3228 - val_mae: 3.5027
Epoch 26/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5500 - mae: 3.5793 - val_loss: 21.1845 - val_mae: 3.5619
Epoch 27/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5382 - mae: 3.5647 - val_loss: 22.3521 - val_mae: 3.6539
Epoch 28/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.3820 - mae: 3.5752 - val_loss: 19.6319 - val_mae: 3.4370
Epoch 29/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0346 - mae: 3.5224 - val_loss: 21.7864 - val_mae: 3.5894
Epoch 30/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.2157 - mae: 3.5488 - val_loss: 21.5257 - val_mae: 3.5745
Epoch 31/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0587 - mae: 3.5216 - val_loss: 19.6803 - val_mae: 3.4362
Epoch 32/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0729 - mae: 3.5191 - val_loss: 19.5552 - val_mae: 3.4393
Epoch 33/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19.9574 - mae: 3.5196 - val_loss: 19.6087 - val_mae: 3.4265
Epoch 34/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.3528 - mae: 3.5404 - val_loss: 19.7229 - val_mae: 3.4169
Epoch 35/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.1371 - mae: 3.5411 - val_loss: 22.3636 - val_mae: 3.6271
Epoch 36/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0076 - mae: 3.5216 - val_loss: 22.3414 - val_mae: 3.6753
Epoch 37/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6873 - mae: 3.5790 - val_loss: 20.5517 - val_mae: 3.5190
Epoch 38/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19.9472 - mae: 3.4995 - val_loss: 19.1159 - val_mae: 3.3612
Epoch 39/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19.6696 - mae: 3.4866 - val_loss: 19.7416 - val_mae: 3.4520
Epoch 40/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.4179 - mae: 3.5398 - val_loss: 19.9598 - val_mae: 3.4481
Epoch 41/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.1462 - mae: 3.5140 - val_loss: 19.4539 - val_mae: 3.3880
Epoch 42/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19.5152 - mae: 3.4713 - val_loss: 22.3755 - val_mae: 3.6686
Epoch 43/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.3657 - mae: 3.5392 - val_loss: 20.2478 - val_mae: 3.4666
Epoch 44/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0292 - mae: 3.5071 - val_loss: 21.8753 - val_mae: 3.6484
Epoch 45/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0939 - mae: 3.5120 - val_loss: 19.2818 - val_mae: 3.4018
Epoch 46/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.0843 - mae: 3.5049 - val_loss: 23.7096 - val_mae: 3.6956
Epoch 47/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 19.9260 - mae: 3.4739 - val_loss: 21.5634 - val_mae: 3.5628
Epoch 48/200
179/179 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.2447 - mae: 3.5266 - val_loss: 22.1925 - val_mae: 3.6711

In [31]:
import matplotlib.pyplot as plt
plt.plot(nn.history['loss'],label='Training Loss')
plt.plot(nn.history['val_loss'],label='Validation Loss')
plt.title("Learning Curve")
plt.xlabel("Number of Epochs")
plt.ylabel("Loss mse")
plt.legend()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

## Model Evaluation

In [32]:
model.evaluate(xtrain,ytrain)

224/224 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.0117 - mae: 3.6739

[22.011695861816406, 3.6738531589508057]

In [33]:
model.evaluate(xtest,ytest)

75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.8982 - mae: 3.6589

[21.898160934448242, 3.6588690280914307]

## Model Evaluation — R2 Score

In [34]:
from sklearn.metrics import r2_score
ypred = model.predict(xtest)
print("R2 Score:", r2_score(ytest, ypred))

75/75 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
R2 Score: 0.926581859588623

## R2 score is 93% , so this model will perform well

In [35]:
# pip install joblib
import joblib

# save the pipeline - data cleaning and data preprocessing
joblib.dump(pre,'PowerPlant_model_pre.joblib')

# save model
model.save("PowerPlant_model.keras")

In [39]:
from keras.models import load_model
m1 = load_model("PowerPlant_model.keras")
m1.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,837 (34.52 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,892 (23.02 KB)